//RICARDO SAMPAIO MARCHEZAN

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ricar
 */
public class FormPrincipal extends javax.swing.JFrame {
    //MÉTODO SINGLETON
private static FormPrincipal instance;
public static FormPrincipal getInstance() {
    if (instance == null) {
        instance = new FormPrincipal();
    }
    return instance;
}


    /**
     * Creates new form FormPrincipal
     */
    private FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        MenuBar = new javax.swing.JMenuBar();
        MenuCadastro = new javax.swing.JMenu();
        menuCadVuc = new javax.swing.JMenuItem();
        menuCadToco = new javax.swing.JMenuItem();
        menuCadTruck = new javax.swing.JMenuItem();
        MenuRelatorios = new javax.swing.JMenu();
        menuRelVuc = new javax.swing.JMenuItem();
        menuRelToco = new javax.swing.JMenuItem();
        menuRelTruck = new javax.swing.JMenuItem();
        MenuSair = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuCadastro.setText("Cadastros");

        menuCadVuc.setText("VUC");
        menuCadVuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadVucActionPerformed(evt);
            }
        });
        MenuCadastro.add(menuCadVuc);

        menuCadToco.setText("TOCO");
        menuCadToco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadTocoActionPerformed(evt);
            }
        });
        MenuCadastro.add(menuCadToco);

        menuCadTruck.setText("TRUCK");
        menuCadTruck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadTruckActionPerformed(evt);
            }
        });
        MenuCadastro.add(menuCadTruck);

        MenuBar.add(MenuCadastro);

        MenuRelatorios.setText("Relatorios");

        menuRelVuc.setText("RelatorioVuc");
        menuRelVuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelVucActionPerformed(evt);
            }
        });
        MenuRelatorios.add(menuRelVuc);

        menuRelToco.setText("RelatorioToco");
        menuRelToco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelTocoActionPerformed(evt);
            }
        });
        MenuRelatorios.add(menuRelToco);

        menuRelTruck.setText("RelatorioTruck");
        menuRelTruck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelTruckActionPerformed(evt);
            }
        });
        MenuRelatorios.add(menuRelTruck);

        MenuBar.add(MenuRelatorios);

        MenuSair.setText("Sair");

        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        MenuSair.add(menuSair);

        MenuBar.add(MenuSair);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadVucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadVucActionPerformed
        FormVuc.getInstance().setVisible(true);
    }//GEN-LAST:event_menuCadVucActionPerformed

    private void menuCadTocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadTocoActionPerformed
        FormToco.getInstance().setVisible(true);
    }//GEN-LAST:event_menuCadTocoActionPerformed

    private void menuCadTruckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadTruckActionPerformed
        FormTruck.getInstance().setVisible(true);
    }//GEN-LAST:event_menuCadTruckActionPerformed

    private void menuRelVucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelVucActionPerformed
       FormRelVuc.getInstance().atualizarTabela().setVisible(true);
    }//GEN-LAST:event_menuRelVucActionPerformed

    private void menuRelTocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelTocoActionPerformed
       FormRelToco.getInstance().atualizarTabela().setVisible(true);
    }//GEN-LAST:event_menuRelTocoActionPerformed

    private void menuRelTruckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelTruckActionPerformed
        FormRelTruck.getInstance().atualizarTabela().setVisible(true);
        
    }//GEN-LAST:event_menuRelTruckActionPerformed

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
    FormPrincipal.getInstance().setVisible(true);
});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu MenuCadastro;
    private javax.swing.JMenu MenuRelatorios;
    private javax.swing.JMenu MenuSair;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem menuCadToco;
    private javax.swing.JMenuItem menuCadTruck;
    private javax.swing.JMenuItem menuCadVuc;
    private javax.swing.JMenuItem menuRelToco;
    private javax.swing.JMenuItem menuRelTruck;
    private javax.swing.JMenuItem menuRelVuc;
    private javax.swing.JMenuItem menuSair;
    // End of variables declaration//GEN-END:variables
}
